server:
  port: 8080

spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: utf-8
  mode: html5
  servlet:
    content-type: text/html


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.cpy.springbootdemo.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
